FROM ubuntu:22.04
RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
    build-essential binutils cmake ninja-build pkg-config cargo curl ca-certificates bzip2 \
    libgtk-3-dev libxi-dev libnss3-dev libasound2-dev libatk-bridge2.0-dev \
    libxss-dev libxtst-dev libdrm-dev libgbm-dev libxkbcommon-dev libcups2-dev \
    && rm -rf /var/lib/apt/lists/*
